# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("students", "0014_parent_organization_student_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("parents", "Parents Only"),
                            ("teachers", "Teachers Only"),
                            ("students", "Students Only"),
                            ("staff", "Staff Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "send_sms",
                    models.BooleanField(default=False, help_text="Send via SMS"),
                ),
                (
                    "send_email",
                    models.BooleanField(default=False, help_text="Send via Email"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When announcement was sent", null=True
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "sms_count",
                    models.IntegerField(default=0, help_text="Number of SMS sent"),
                ),
                (
                    "email_count",
                    models.IntegerField(default=0, help_text="Number of emails sent"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this announcement belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recipient_phone",
                    models.CharField(
                        help_text="Phone number in format 254XXXXXXXXX", max_length=15
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sending failed"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="Purpose of SMS (e.g., 'fee_reminder', 'announcement', 'attendance_alert')",
                        max_length=100,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this SMS notification belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sms_notifications",
                        to="core.organization",
                    ),
                ),
                (
                    "related_announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_notifications",
                        to="communications.announcement",
                    ),
                ),
                (
                    "related_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_notifications",
                        to="students.student",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sms_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="sms_notific_organiz_133ede_idx",
                    ),
                    models.Index(
                        fields=["recipient_phone", "created_at"],
                        name="sms_notific_recipie_33f1dc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Fee Reminder', 'Attendance Alert')",
                        max_length=100,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[("sms", "SMS Template"), ("email", "Email Template")],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject (for email templates)",
                        max_length=200,
                    ),
                ),
                (
                    "template_text",
                    models.TextField(
                        help_text="Template text with variables like {{student_name}}, {{amount}}, etc."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of available variables (e.g., ['student_name', 'amount', 'due_date'])",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of when to use this template"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this template belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_templates",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["name"],
                "unique_together": {("organization", "name", "template_type")},
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sending failed"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="Purpose of email (e.g., 'fee_reminder', 'announcement')",
                        max_length=100,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this email notification belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="email_notifications",
                        to="core.organization",
                    ),
                ),
                (
                    "related_announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_notifications",
                        to="communications.announcement",
                    ),
                ),
                (
                    "related_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_notifications",
                        to="students.student",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="email_notif_organiz_f58d0a_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "created_at"],
                        name="email_notif_recipie_8196c1_idx",
                    ),
                ],
            },
        ),
    ]
