# Generated by Django 4.2.13 on 2025-12-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_unallocated_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-PESA"),
                    ("equity_bank", "Equity Bank"),
                    ("coop_bank", "Co-operative Bank"),
                    ("manual_entry", "Manual Entry"),
                    ("cheque", "Cheque"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
