# Generated by Django 4.2.13 on 2025-12-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_payment_method_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_source",
            field=models.CharField(
                choices=[
                    ("equity_bank", "Equity Bank"),
                    ("coop_bank", "Co-operative Bank"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
