# Generated by Django 4.2.13 on 2025-12-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_payment_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_source",
            field=models.CharField(
                choices=[
                    ("equity_bank", "Equity Bank"),
                    ("coop_bank", "Co-operative Bank"),
                    ("mpesa", "Mpesa"),
                ],
                max_length=20,
            ),
        ),
    ]
