# Generated by Django 4.2.13 on 2025-12-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_payment_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("mobile_money", "Mobile Money"),
                    ("bank_deposit", "Bank Deposit"),
                    ("cheque", "Cheque"),
                ],
                max_length=20,
            ),
        ),
    ]
