# Generated by Django 4.2.13 on 2026-01-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_source",
            field=models.CharField(
                choices=[
                    ("equity_bank", "Equity Bank"),
                    ("coop_bank", "Co-operative Bank"),
                    ("mpesa", "Mpesa"),
                    ("credit", "Student Credit"),
                ],
                max_length=20,
            ),
        ),
    ]
