# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("payments", "0008_alter_payment_payment_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this payment belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.organization",
            ),
        ),
    ]
