# Generated by Django 4.2.13 on 2025-12-02 07:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?254\\d{9}$", "Enter a valid Kenyan phone number"
                            )
                        ],
                    ),
                ),
                ("phone_secondary", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("town", models.CharField(blank=True, max_length=50)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("employer", models.CharField(blank=True, max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("sponsor", "Sponsor"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "parents",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("admission_number", models.CharField(max_length=20, unique=True)),
                ("admission_date", models.DateField()),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "birth_certificate_number",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Allergies, chronic conditions, etc."
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                ("previous_school", models.CharField(blank=True, max_length=100)),
                ("previous_class", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred"),
                            ("suspended", "Suspended"),
                            ("expelled", "Expelled"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("status_date", models.DateField(blank=True, null=True)),
                ("status_reason", models.TextField(blank=True)),
                ("has_special_needs", models.BooleanField(default=False)),
                ("special_needs_details", models.TextField(blank=True)),
                ("uses_school_transport", models.BooleanField(default=False)),
                ("is_boarder", models.BooleanField(default=False)),
                ("dormitory", models.CharField(blank=True, max_length=50)),
                (
                    "current_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.class",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["admission_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("sponsor", "Sponsor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_emergency_contact", models.BooleanField(default=False)),
                ("can_pickup", models.BooleanField(default=True)),
                ("receives_notifications", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_students",
                        to="students.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_parents",
                "unique_together": {("student", "parent")},
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("transfer_letter", "Transfer Letter"),
                            ("report_card", "Previous Report Card"),
                            ("medical_report", "Medical Report"),
                            ("passport_photo", "Passport Photo"),
                            ("immunization", "Immunization Record"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="student_documents/")),
                ("description", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_documents",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="parents",
            field=models.ManyToManyField(
                related_name="children",
                through="students.StudentParent",
                to="students.parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.transportroute",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("record_date", models.DateField()),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("checkup", "Health Checkup"),
                            ("illness", "Illness"),
                            ("injury", "Injury"),
                            ("vaccination", "Vaccination"),
                            ("allergy", "Allergy"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("treatment", models.TextField(blank=True)),
                ("prescribed_medication", models.TextField(blank=True)),
                ("doctor_name", models.CharField(blank=True, max_length=100)),
                ("hospital_clinic", models.CharField(blank=True, max_length=100)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["-record_date"],
            },
        ),
        migrations.CreateModel(
            name="DisciplineRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("minor", "Minor Infraction"),
                            ("major", "Major Infraction"),
                            ("positive", "Positive Behavior"),
                            ("warning", "Warning"),
                            ("suspension", "Suspension"),
                        ],
                        max_length=20,
                    ),
                ),
                ("incident_date", models.DateField()),
                ("description", models.TextField()),
                ("action_taken", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_notified_date", models.DateField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "discipline_records",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="students_admissi_664d58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_class", "status"], name="students_current_0a52e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["last_name", "first_name"], name="students_last_na_08ef26_idx"
            ),
        ),
    ]
