# Generated by Django 4.2.13 on 2025-12-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("guardian", "Guardian"),
                    ("sponsor", "Sponsor"),
                    ("other", "Other"),
                ],
                default="guardian",
                max_length=20,
            ),
        ),
    ]
