# Generated by Django 4.2.13 on 2025-12-18 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_parent_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="credit_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Positive = owes money (debt), Negative = has credit (prepayment)",
                max_digits=10,
            ),
        ),
    ]
