# Generated by Django 4.2.13 on 2025-12-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_credit_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="dormitory",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_boarder",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status_reason",
        ),
    ]
