# Generated by Django 4.2.13 on 2025-12-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_remove_transportroute_afternoon_departure_and_more"),
        (
            "students",
            "0004_remove_student_dormitory_remove_student_is_boarder_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                default="A",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.transportroute",
            ),
        ),
    ]
