# Generated by Django 4.2.13 on 2025-12-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_remove_transportroute_code_alter_transportroute_name"),
        ("students", "0005_alter_student_transport_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.transportroute",
            ),
        ),
    ]
