# Generated by Django 4.2.13 on 2025-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_student_transport_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="assessment_number",
            field=models.CharField(
                blank=True, help_text="Assessment/Examination number", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="residence",
            field=models.CharField(
                blank=True, help_text="Student's residence area/estate", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="transport_pickup_person",
            field=models.CharField(
                blank=True,
                help_text="Person authorized to pick up the student from the bus",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="upi_number",
            field=models.CharField(
                blank=True,
                help_text="Unique Pupil Identifier (NEMIS/Ministry of Education)",
                max_length=30,
            ),
        ),
    ]
