# Generated by Django 4.2.13 on 2025-12-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_add_transport_upi_assessment_residence_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when the status was last changed", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="status_reason",
            field=models.TextField(blank=True, help_text="Reason for status change"),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                    ("suspended", "Suspended"),
                    ("expelled", "Expelled"),
                    ("withdrawn", "Withdrawn"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
