# Generated by Django 4.2.13 on 2025-12-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
        ("students", "0008_add_status_date_reason_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="transport.transportroute",
            ),
        ),
    ]
