# Generated by Django 4.2.13 on 2025-12-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_student_transport_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
