# Generated by Django 4.2.13 on 2026-01-13 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_make_admission_number_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="balance_bf_original",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Frozen debt from previous term at term start (positive value). Never changes during the term.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="prepayment_original",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Frozen prepayment from previous term at term start (positive value). Never changes during the term.",
                max_digits=10,
            ),
        ),
    ]
