# Generated by Django 4.2.13 on 2026-01-15 06:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_add_student_frozen_balance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="outstanding_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of balances of all unpaid, active invoices",
                max_digits=12,
            ),
        ),
    ]
