# Generated by Django 4.2.13 on 2026-01-19 05:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_student_outstanding_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="credit_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
