# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("students", "0013_alter_student_credit_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this parent belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parents",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this student belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="core.organization",
            ),
        ),
    ]
