# Generated by Django 4.2.13 on 2026-03-21 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        (
            "academics",
            "0012_academicyear_organization_attendance_organization_and_more",
        ),
        ("students", "0014_parent_organization_student_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this club belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubs",
                        to="core.organization",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clubs_led",
                        to="academics.staff",
                    ),
                ),
            ],
            options={
                "db_table": "clubs",
                "ordering": ["name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_on", models.DateField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="students.club",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "club_memberships",
                "ordering": ["club__name", "student__admission_number"],
                "unique_together": {("student", "club")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="clubs",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="students.ClubMembership",
                to="students.club",
            ),
        ),
    ]
