# Generated by Django 4.2.13 on 2026-05-01 03:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportfee_organization_and_more'),
        ('academics', '0014_termtransitionlog_alter_term_unique_together_and_more'),
        ('core', '0001_initial'),
        ('students', '0016_student_deleted_at_student_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('expelled', 'Expelled'), ('withdrawn', 'Withdrawn'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('uses_school_transport', models.BooleanField(default=False)),
                ('transport_trip_type', models.CharField(blank=True, choices=[('full', 'Full Trip'), ('half', 'Half Trip')], default='full', max_length=10)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_term_states', to='academics.class')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_term_states', to='core.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_states', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='academics.term')),
                ('transport_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_term_states', to='transport.transportroute')),
            ],
            options={
                'db_table': 'student_term_states',
                'ordering': ['term', 'student__admission_number'],
                'indexes': [models.Index(fields=['term', 'status'], name='student_ter_term_id_28b01a_idx'), models.Index(fields=['organization', 'term', 'status'], name='student_ter_organiz_07d3b7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studenttermstate',
            constraint=models.UniqueConstraint(fields=('organization', 'student', 'term'), name='unique_student_state_per_org_term'),
        ),
    ]
