# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique organization code", max_length=50, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo_url",
                    models.URLField(blank=True, help_text="URL to organization logo"),
                ),
                (
                    "sms_account_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique SMS account number for KCB payments (e.g., SMS001)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sms_balance",
                    models.IntegerField(
                        default=0, help_text="Current SMS credits balance"
                    ),
                ),
                (
                    "sms_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Price per SMS credit in KSH",
                        max_digits=10,
                    ),
                ),
                (
                    "imarabiz_shortcode",
                    models.CharField(
                        blank=True,
                        default="SWIFT_RE_TECH",
                        help_text="ImaraBiz SMS shortcode for this organization",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
    ]
