# Generated by Django 4.2.13 on 2025-12-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("tuition", "Tuition"),
                    ("boarding", "Boarding"),
                    ("transport", "Transport"),
                    ("meals", "Meals/Lunch"),
                    ("uniform", "Uniform"),
                    ("books", "Books & Stationery"),
                    ("examination", "Examination"),
                    ("activity", "Activity/Extra-curricular"),
                    ("development", "Development Levy"),
                    ("admission", "Admission Fee"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("tuition", "Tuition"),
                    ("boarding", "Boarding"),
                    ("transport", "Transport"),
                    ("meals", "Meals/Lunch"),
                    ("uniform", "Uniform"),
                    ("books", "Books & Stationery"),
                    ("examination", "Examination"),
                    ("activity", "Activity/Extra-curricular"),
                    ("development", "Development Levy"),
                    ("admission", "Admission Fee"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
