# Generated by Django 4.2.13 on 2025-12-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_feeitem_category_alter_invoiceitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fee_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="finance.feestructure",
            ),
        ),
    ]
