# Generated by Django 4.2.13 on 2025-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoice_fee_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="overdue",
                max_length=20,
            ),
        ),
    ]
