# Generated by Django 4.2.13 on 2025-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feestructure",
            name="is_boarding",
        ),
    ]
