# Generated by Django 4.2.13 on 2025-12-21 10:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0008_transportfee_half_amount_alter_transportfee_amount_and_more",
        ),
        ("finance", "0005_remove_feestructure_is_boarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="academics.transportroute",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="transport_trip_type",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full Trip"), ("half", "Half Trip")],
                help_text="If set and category=='transport', indicates half/full trip",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("tuition", "Tuition"),
                    ("boarding", "Boarding"),
                    ("transport", "Transport"),
                    ("meals", "Meals/Lunch"),
                    ("uniform", "Uniform"),
                    ("books", "Books & Stationery"),
                    ("examination", "Examination"),
                    ("activity", "Activity/Extra-curricular"),
                    ("development", "Development Levy"),
                    ("admission", "Admission Fee"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="discount_applied",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="fee_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="finance.feeitem",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
