# Generated by Django 4.2.13 on 2025-12-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
        ("finance", "0006_invoiceitem_transport_route_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="transport_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="transport.transportroute",
            ),
        ),
    ]
