# Generated by Django 4.2.13 on 2026-01-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_alter_invoice_balance_bf_original"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="balance_bf_original",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
