# Generated by Django 4.2.13 on 2026-01-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_alter_invoice_balance_bf_original"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_invoice_7778bc_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_student_7e7032_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="invoices_status_07776b_idx",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="balance_bf_original",
        ),
    ]
