# Generated by Django 4.2.13 on 2026-01-19 05:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_remove_invoice_invoices_invoice_7778bc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="balance_bf_original",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
