# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("finance", "0015_alter_feeitem_category_alter_invoiceitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this discount belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discounts",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this fee structure belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this invoice belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core.organization",
            ),
        ),
    ]
