# Generated by Django 4.2.11 on 2026-03-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_invoice_deleted_at_invoice_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitem',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('boarding', 'Boarding'), ('transport', 'Transport'), ('meals', 'Meals/Lunch'), ('uniform', 'Uniform'), ('books', 'Books & Stationery'), ('examination', 'Examination'), ('activity', 'Activity/Extra-curricular'), ('development', 'Development Levy'), ('admission', 'Admission Fee'), ('other', 'Educational Activities'), ('balance_bf', 'Balance Brought Forward'), ('prepayment', 'Prepayment / Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('boarding', 'Boarding'), ('transport', 'Transport'), ('meals', 'Meals/Lunch'), ('uniform', 'Uniform'), ('books', 'Books & Stationery'), ('examination', 'Examination'), ('activity', 'Activity/Extra-curricular'), ('development', 'Development Levy'), ('admission', 'Admission Fee'), ('other', 'Educational Activities'), ('balance_bf', 'Balance Brought Forward'), ('prepayment', 'Prepayment / Credit')], max_length=50),
        ),
    ]
