# reports/views_exports.py
import io
from decimal import Decimal
from datetime import datetime

from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.conf import settings
from django.db.models import Sum, Value
from django.db.models.functions import Coalesce

import openpyxl
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, Alignment, Border, Side, numbers

# WeasyPrint for PDF
from weasyprint import HTML

# Import models used by the reports - adjust import paths if needed
from finance.models import Invoice, InvoiceItem
from payments.models import Payment  # adjust if your Payment model name differs
from academics.models import TransportRoute  # used for transport route names


# ---------- Helpers ----------
def xlsx_response(workbook_bytes, filename):
    response = HttpResponse(workbook_bytes, content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response


def workbook_to_bytes(wb):
    bio = io.BytesIO()
    wb.save(bio)
    bio.seek(0)
    return bio.getvalue()


def format_money_cell(cell):
    # Use Kenyan Shilling formatting as example; change to suits you
    cell.number_format = '#,##0.00'


def add_common_header(ws, title):
    # Title row
    ws.merge_cells('A1:G1')
    ws['A1'] = getattr(settings, 'SCHOOL_NAME', 'School')
    ws['A1'].font = Font(size=14, bold=True)
    ws['A1'].alignment = Alignment(horizontal='center')
    ws.merge_cells('A2:G2')
    ws['A2'] = title
    ws['A2'].font = Font(size=12, bold=True)
    ws['A2'].alignment = Alignment(horizontal='center')
    # small meta row
    ws.merge_cells('A3:G3')
    ws['A3'] = f'Generated by: {""} on {datetime.now().strftime("%d %b %Y %H:%M")}'
    ws['A3'].font = Font(size=9)
    ws['A3'].alignment = Alignment(horizontal='center')


# ---------- Outstanding Balances Exports ----------
class OutstandingBalancesExcelView(LoginRequiredMixin, View):
    """
    Exports Outstanding Balances (per-student aggregated) to Excel.
    Accepts same GET params as the on-screen report (academic_year, term, start_date, end_date, student_class, balance_operator, balance_amount).
    """

    def get(self, request):
        # Use same filter logic as your OutstandingBalancesReportView
        from .forms import OutstandingBalancesFilterForm  # import here to avoid circular import
        form = OutstandingBalancesFilterForm(request.GET or None)
        if not form.is_valid():
            return HttpResponseBadRequest("Invalid filters")

        # extract filters (same keys used earlier)
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')
        academic_year = form.cleaned_data.get('academic_year')
        term = form.cleaned_data.get('term')
        student_class = form.cleaned_data.get('student_class')
        balance_op = form.cleaned_data.get('balance_operator') or 'any'
        balance_amt = form.cleaned_data.get('balance_amount') or Decimal('0.00')
        include_zero = form.cleaned_data.get('show_zero_balances')

        invoices = Invoice.objects.select_related('student', 'term__academic_year')

        if academic_year:
            invoices = invoices.filter(term__academic_year=academic_year)
            if term:
                invoices = invoices.filter(term__term=term)
        if start_date:
            invoices = invoices.filter(issue_date__gte=start_date)
        if end_date:
            invoices = invoices.filter(issue_date__lte=end_date)
        if student_class:
            invoices = invoices.filter(student__current_class=student_class)

        annotations = {
            'total_billed': Coalesce(Sum('total_amount'), Value(0)),
            'total_paid': Coalesce(Sum('amount_paid'), Value(0)),
            'total_balance': Coalesce(Sum('balance'), Value(0)),
            'total_balance_bf': Coalesce(Sum('balance_bf'), Value(0)),
            'total_prepayment': Coalesce(Sum('prepayment'), Value(0)),
        }

        grouped_qs = invoices.values(
            'student__pk',
            'student__admission_number',
            'student__full_name',
            'student__current_class',
            'student__contacts',
            'term__academic_year__year',
        ).annotate(**annotations).order_by('-total_balance', 'student__full_name')

        # balance filter
        if balance_op != 'any' and balance_amt is not None:
            lookup = {
                '=': 'total_balance',
                '>': 'total_balance__gt',
                '<': 'total_balance__lt',
                '>=': 'total_balance__gte',
                '<=': 'total_balance__lte',
            }.get(balance_op, None)
            if lookup:
                grouped_qs = grouped_qs.filter(**{lookup: balance_amt})

        if not include_zero:
            grouped_qs = grouped_qs.exclude(total_balance=Decimal('0.00'))

        rows = list(grouped_qs)

        # Build Excel
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Outstanding Balances"

        add_common_header(ws, "Outstanding Balances Report")

        headers = ['Year', 'Admission No', 'Name', 'Class', 'Contacts', 'Prepayment', 'Balance B/F', 'Balance', 'Paid', 'Total Billed']
        for c, h in enumerate(headers, start=1):
            cell = ws.cell(row=5, column=c, value=h)
            cell.font = Font(bold=True)

        row_num = 6
        for r in rows:
            ws.cell(row=row_num, column=1, value=r.get('term__academic_year__year'))
            ws.cell(row=row_num, column=2, value=r.get('student__admission_number'))
            ws.cell(row=row_num, column=3, value=r.get('student__full_name'))
            ws.cell(row=row_num, column=4, value=r.get('student__current_class'))
            ws.cell(row=row_num, column=5, value=r.get('student__contacts') or "")
            c6 = ws.cell(row=row_num, column=6, value=float(r.get('total_prepayment') or 0))
            format_money_cell(c6)
            c7 = ws.cell(row=row_num, column=7, value=float(r.get('total_balance_bf') or 0))
            format_money_cell(c7)
            c8 = ws.cell(row=row_num, column=8, value=float(r.get('total_balance') or 0))
            format_money_cell(c8)
            c9 = ws.cell(row=row_num, column=9, value=float(r.get('total_paid') or 0))
            format_money_cell(c9)
            c10 = ws.cell(row=row_num, column=10, value=float(r.get('total_billed') or 0))
            format_money_cell(c10)
            row_num += 1

        # Totals row
        totals = {
            'total_prepayment': sum((r['total_prepayment'] or Decimal('0.00')) for r in rows),
            'total_balance_bf': sum((r['total_balance_bf'] or Decimal('0.00')) for r in rows),
            'total_balance': sum((r['total_balance'] or Decimal('0.00')) for r in rows),
            'total_paid': sum((r['total_paid'] or Decimal('0.00')) for r in rows),
            'total_billed': sum((r['total_billed'] or Decimal('0.00')) for r in rows),
        }
        ws.cell(row=row_num, column=1, value='Totals').font = Font(bold=True)
        c6 = ws.cell(row=row_num, column=6, value=float(totals['total_prepayment']))
        format_money_cell(c6)
        c7 = ws.cell(row=row_num, column=7, value=float(totals['total_balance_bf']))
        format_money_cell(c7)
        c8 = ws.cell(row=row_num, column=8, value=float(totals['total_balance']))
        format_money_cell(c8)
        c9 = ws.cell(row=row_num, column=9, value=float(totals['total_paid']))
        format_money_cell(c9)
        c10 = ws.cell(row=row_num, column=10, value=float(totals['total_billed']))
        format_money_cell(c10)

        # Auto width columns
        for col in range(1, len(headers) + 1):
            ws.column_dimensions[get_column_letter(col)].width = 18

        bytes_data = workbook_to_bytes(wb)
        filename = f"outstanding-balances-{datetime.now().strftime('%Y%m%d-%H%M')}.xlsx"
        return xlsx_response(bytes_data, filename)


class OutstandingBalancesPDFView(LoginRequiredMixin, View):
    """
    Renders the aggregated outstanding balances to PDF using a PDF template.
    """

    def get(self, request):
        from .forms import OutstandingBalancesFilterForm
        form = OutstandingBalancesFilterForm(request.GET or None)
        if not form.is_valid():
            return HttpResponseBadRequest("Invalid filters")

        # Use the same queryset logic as Excel view
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')
        academic_year = form.cleaned_data.get('academic_year')
        term = form.cleaned_data.get('term')
        student_class = form.cleaned_data.get('student_class')
        balance_op = form.cleaned_data.get('balance_operator') or 'any'
        balance_amt = form.cleaned_data.get('balance_amount') or Decimal('0.00')
        include_zero = form.cleaned_data.get('show_zero_balances')

        invoices = Invoice.objects.select_related('student', 'term__academic_year')
        if academic_year:
            invoices = invoices.filter(term__academic_year=academic_year)
            if term:
                invoices = invoices.filter(term__term=term)
        if start_date:
            invoices = invoices.filter(issue_date__gte=start_date)
        if end_date:
            invoices = invoices.filter(issue_date__lte=end_date)
        if student_class:
            invoices = invoices.filter(student__current_class=student_class)

        annotations = {
            'total_billed': Coalesce(Sum('total_amount'), Value(0)),
            'total_paid': Coalesce(Sum('amount_paid'), Value(0)),
            'total_balance': Coalesce(Sum('balance'), Value(0)),
            'total_balance_bf': Coalesce(Sum('balance_bf'), Value(0)),
            'total_prepayment': Coalesce(Sum('prepayment'), Value(0)),
        }

        grouped_qs = invoices.values(
            'student__pk',
            'student__admission_number',
            'student__full_name',
            'student__current_class',
            'student__contacts',
            'term__academic_year__year',
        ).annotate(**annotations).order_by('-total_balance', 'student__full_name')

        if balance_op != 'any' and balance_amt is not None:
            lookup = {
                '=': 'total_balance',
                '>': 'total_balance__gt',
                '<': 'total_balance__lt',
                '>=': 'total_balance__gte',
                '<=': 'total_balance__lte',
            }.get(balance_op, None)
            if lookup:
                grouped_qs = grouped_qs.filter(**{lookup: balance_amt})

        if not include_zero:
            grouped_qs = grouped_qs.exclude(total_balance=Decimal('0.00'))

        rows = list(grouped_qs)
        totals = {
            'total_prepayment': sum((r['total_prepayment'] or Decimal('0.00')) for r in rows),
            'total_balance_bf': sum((r['total_balance_bf'] or Decimal('0.00')) for r in rows),
            'total_balance': sum((r['total_balance'] or Decimal('0.00')) for r in rows),
            'total_paid': sum((r['total_paid'] or Decimal('0.00')) for r in rows),
            'total_billed': sum((r['total_billed'] or Decimal('0.00')) for r in rows),
        }

        context = {
            'rows': rows,
            'totals': totals,
            'filters': {k: form.cleaned_data.get(k) for k in ['start_date', 'end_date', 'academic_year', 'term', 'student_class']},
            'SCHOOL_NAME': getattr(settings, 'SCHOOL_NAME', ''),
            'SCHOOL_LOGO_URL': getattr(settings, 'SCHOOL_LOGO_URL', ''),
            'SCHOOL_ADDRESS': getattr(settings, 'SCHOOL_ADDRESS', ''),
            'SCHOOL_CONTACT': getattr(settings, 'SCHOOL_CONTACT', ''),
            'generated_by': request.user.get_full_name(),
            'generated_on': datetime.now(),
        }

        html_string = render_to_string('reports/pdf/outstanding_report_pdf.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri('/'))
        pdf_bytes = html.write_pdf()
        filename = f"outstanding-balances-{datetime.now().strftime('%Y%m%d-%H%M')}.pdf"
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response


# ---------- Transport Exports ----------
class TransportReportExcelView(LoginRequiredMixin, View):
    """
    Generates a transport report Excel file. Accepts same GET params as on-screen view (academic_year, term, route, student_class, start_date, end_date, show_zero_rows).
    """
    def get(self, request):
        from .forms import TransportReportFilterForm
        form = TransportReportFilterForm(request.GET or None)
        if not form.is_valid():
            return HttpResponseBadRequest("Invalid filters")

        academic_year = form.cleaned_data['academic_year']
        term = form.cleaned_data['term']
        route = form.cleaned_data.get('route')
        student_class = form.cleaned_data.get('student_class') or ''
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')
        show_zero = form.cleaned_data.get('show_zero_rows', False)

        items_qs = InvoiceItem.objects.filter(
            invoice__term__academic_year=academic_year,
            invoice__term__term=term,
            category='transport'
        ).select_related('invoice__student', 'transport_route')

        if route:
            items_qs = items_qs.filter(transport_route=route)
        if student_class:
            items_qs = items_qs.filter(invoice__student__current_class=student_class)
        if start_date:
            items_qs = items_qs.filter(invoice__issue_date__gte=start_date)
        if end_date:
            items_qs = items_qs.filter(invoice__issue_date__lte=end_date)

        grouped = items_qs.values(
            'invoice__student__pk',
            'invoice__student__full_name',
            'invoice__student__admission_number',
            'invoice__student__current_class',
            'transport_route__pk',
            'transport_route__name'
        ).annotate(total_billed=Coalesce(Sum('net_amount'), Value(0))).order_by('invoice__student__full_name')

        # Build collected_map (try to use Payment allocations if you have them)
        try:
            from finance.models import PaymentAllocation
            alloc_qs = PaymentAllocation.objects.filter(invoice_item__in=items_qs).values(
                'invoice_item__invoice__student__pk',
                'invoice_item__transport_route__pk'
            ).annotate(collected=Coalesce(Sum('amount'), Value(0)))
            collected_map = {}
            for row in alloc_qs:
                key = (row.get('invoice_item__invoice__student__pk'), row.get('invoice_item__transport_route__pk'))
                collected_map[key] = Decimal(row.get('collected') or 0)
        except Exception:
            # fallback proportional allocation
            collected_map = {}
            invoice_ids = items_qs.values_list('invoice_id', flat=True).distinct()
            invoices = Invoice.objects.filter(id__in=invoice_ids)
            for inv in invoices:
                inv_items = items_qs.filter(invoice=inv)
                inv_total_transport = sum((i.net_amount or Decimal('0.00')) for i in inv_items)
                paid = inv.amount_paid or Decimal('0.00')
                if inv_total_transport <= Decimal('0.00'):
                    for it in inv_items:
                        key = (inv.student.pk, it.transport_route.pk if it.transport_route else None)
                        collected_map[key] = collected_map.get(key, Decimal('0.00'))
                    continue
                for it in inv_items:
                    proportion = (it.net_amount or Decimal('0.00')) / inv_total_transport
                    alloc_amount = (paid * proportion).quantize(Decimal('0.01'))
                    key = (inv.student.pk, it.transport_route.pk if it.transport_route else None)
                    collected_map[key] = collected_map.get(key, Decimal('0.00')) + alloc_amount

        # Build rows
        rows = []
        total_billed = Decimal('0.00')
        total_collected = Decimal('0.00')
        total_balance = Decimal('0.00')

        for g in grouped:
            student_pk = g.get('invoice__student__pk')
            billed = Decimal(g.get('total_billed') or 0)
            route_pk = g.get('transport_route__pk')
            collected = collected_map.get((student_pk, route_pk), Decimal('0.00'))
            balance = billed - collected
            if (not show_zero) and billed == Decimal('0.00') and collected == Decimal('0.00'):
                continue
            rows.append({
                'student_name': g.get('invoice__student__full_name') or '',
                'admission': g.get('invoice__student__admission_number') or '',
                'student_class': g.get('invoice__student__current_class') or '',
                'route_name': g.get('transport_route__name') or '',
                'billed': billed,
                'collected': collected,
                'balance': balance,
            })
            total_billed += billed
            total_collected += collected
            total_balance += balance

        # Build workbook
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Transport Report"

        add_common_header(ws, "Transport Report")
        headers = ['Student Name', 'Admission #', 'Class/Grade', 'Route/Destination', 'Transport Amount', 'Paid', 'Balance']
        for c, h in enumerate(headers, start=1):
            ws.cell(row=5, column=c, value=h).font = Font(bold=True)

        row_num = 6
        for r in rows:
            ws.cell(row=row_num, column=1, value=r['student_name'])
            ws.cell(row=row_num, column=2, value=r['admission'])
            ws.cell(row=row_num, column=3, value=r['student_class'])
            ws.cell(row=row_num, column=4, value=r['route_name'])
            c5 = ws.cell(row=row_num, column=5, value=float(r['billed']))
            format_money_cell(c5)
            c6 = ws.cell(row=row_num, column=6, value=float(r['collected']))
            format_money_cell(c6)
            c7 = ws.cell(row=row_num, column=7, value=float(r['balance']))
            format_money_cell(c7)
            row_num += 1

        # Totals
        ws.cell(row=row_num, column=1, value='Totals').font = Font(bold=True)
        c5 = ws.cell(row=row_num, column=5, value=float(total_billed))
        format_money_cell(c5)
        c6 = ws.cell(row=row_num, column=6, value=float(total_collected))
        format_money_cell(c6)
        c7 = ws.cell(row=row_num, column=7, value=float(total_balance))
        format_money_cell(c7)

        for col in range(1, len(headers) + 1):
            ws.column_dimensions[get_column_letter(col)].width = 18

        bytes_data = workbook_to_bytes(wb)
        filename = f"transport-report-{datetime.now().strftime('%Y%m%d-%H%M')}.xlsx"
        return xlsx_response(bytes_data, filename)


class TransportReportPDFView(LoginRequiredMixin, View):
    def get(self, request):
        from .forms import TransportReportFilterForm
        form = TransportReportFilterForm(request.GET or None)
        if not form.is_valid():
            return HttpResponseBadRequest("Invalid filters")

        academic_year = form.cleaned_data['academic_year']
        term = form.cleaned_data['term']
        route = form.cleaned_data.get('route')
        student_class = form.cleaned_data.get('student_class') or ''
        start_date = form.cleaned_data.get('start_date')
        end_date = form.cleaned_data.get('end_date')
        show_zero = form.cleaned_data.get('show_zero_rows', False)

        items_qs = InvoiceItem.objects.filter(
            invoice__term__academic_year=academic_year,
            invoice__term__term=term,
            category='transport'
        ).select_related('invoice__student', 'transport_route')

        if route:
            items_qs = items_qs.filter(transport_route=route)
        if student_class:
            items_qs = items_qs.filter(invoice__student__current_class=student_class)
        if start_date:
            items_qs = items_qs.filter(invoice__issue_date__gte=start_date)
        if end_date:
            items_qs = items_qs.filter(invoice__issue_date__lte=end_date)

        grouped = items_qs.values(
            'invoice__student__pk',
            'invoice__student__full_name',
            'invoice__student__admission_number',
            'invoice__student__current_class',
            'transport_route__pk',
            'transport_route__name'
        ).annotate(total_billed=Coalesce(Sum('net_amount'), Value(0))).order_by('invoice__student__full_name')

        # collected map same logic
        try:
            from finance.models import PaymentAllocation
            alloc_qs = PaymentAllocation.objects.filter(invoice_item__in=items_qs).values(
                'invoice_item__invoice__student__pk',
                'invoice_item__transport_route__pk'
            ).annotate(collected=Coalesce(Sum('amount'), Value(0)))
            collected_map = {}
            for row in alloc_qs:
                key = (row.get('invoice_item__invoice__student__pk'), row.get('invoice_item__transport_route__pk'))
                collected_map[key] = Decimal(row.get('collected') or 0)
        except Exception:
            collected_map = {}
            invoice_ids = items_qs.values_list('invoice_id', flat=True).distinct()
            invoices = Invoice.objects.filter(id__in=invoice_ids)
            for inv in invoices:
                inv_items = items_qs.filter(invoice=inv)
                inv_total_transport = sum((i.net_amount or Decimal('0.00')) for i in inv_items)
                paid = inv.amount_paid or Decimal('0.00')
                if inv_total_transport <= Decimal('0.00'):
                    for it in inv_items:
                        key = (inv.student.pk, it.transport_route.pk if it.transport_route else None)
                        collected_map[key] = collected_map.get(key, Decimal('0.00'))
                    continue
                for it in inv_items:
                    proportion = (it.net_amount or Decimal('0.00')) / inv_total_transport
                    alloc_amount = (paid * proportion).quantize(Decimal('0.01'))
                    key = (inv.student.pk, it.transport_route.pk if it.transport_route else None)
                    collected_map[key] = collected_map.get(key, Decimal('0.00')) + alloc_amount

        rows = []
        total_billed = Decimal('0.00')
        total_collected = Decimal('0.00')
        total_balance = Decimal('0.00')
        for g in grouped:
            student_pk = g.get('invoice__student__pk')
            billed = Decimal(g.get('total_billed') or 0)
            route_pk = g.get('transport_route__pk')
            collected = collected_map.get((student_pk, route_pk), Decimal('0.00'))
            balance = billed - collected
            if (not show_zero) and billed == Decimal('0.00') and collected == Decimal('0.00'):
                continue
            rows.append({
                'student_name': g.get('invoice__student__full_name') or '',
                'admission': g.get('invoice__student__admission_number') or '',
                'student_class': g.get('invoice__student__current_class') or '',
                'route_name': g.get('transport_route__name') or '',
                'billed': billed,
                'collected': collected,
                'balance': balance
            })
            total_billed += billed
            total_collected += collected
            total_balance += balance

        context = {
            'rows': rows,
            'totals': {'billed': total_billed, 'collected': total_collected, 'balance': total_balance},
            'filters': {k: form.cleaned_data.get(k) for k in ['academic_year', 'term', 'route', 'student_class', 'start_date', 'end_date']},
            'SCHOOL_NAME': getattr(settings, 'SCHOOL_NAME', ''),
            'SCHOOL_LOGO_URL': getattr(settings, 'SCHOOL_LOGO_URL', ''),
            'SCHOOL_ADDRESS': getattr(settings, 'SCHOOL_ADDRESS', ''),
            'SCHOOL_CONTACT': getattr(settings, 'SCHOOL_CONTACT', ''),
            'generated_by': request.user.get_full_name(),
            'generated_on': datetime.now(),
        }

        html_string = render_to_string('reports/pdf/transport_report_pdf.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri('/'))
        pdf_bytes = html.write_pdf()
        filename = f"transport-report-{datetime.now().strftime('%Y%m%d-%H%M')}.pdf"
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response


# ---------- Invoice Report Exports ----------
class InvoiceReportExcelView(LoginRequiredMixin, View):
    """
    Exports invoice list (per-invoice) to Excel.
    Accepts GET filters: start_date, end_date, academic_year, term, student_class
    """
    def get(self, request):
        # Basic filters: reuse form if you have one; otherwise parse GET
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        academic_year = request.GET.get('academic_year')
        term = request.GET.get('term')
        student_class = request.GET.get('student_class')

        invoices = Invoice.objects.select_related('student', 'term__academic_year').all()
        if academic_year:
            invoices = invoices.filter(term__academic_year__pk=academic_year)
        if term:
            invoices = invoices.filter(term__term=term)
        if start_date:
            invoices = invoices.filter(issue_date__gte=start_date)
        if end_date:
            invoices = invoices.filter(issue_date__lte=end_date)
        if student_class:
            invoices = invoices.filter(student__current_class=student_class)

        # Build workbook
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Invoices"

        add_common_header(ws, "Invoice Report")
        headers = ['Invoice #', 'Issue Date', 'Student', 'Admission #', 'Class', 'Total Amount', 'Paid', 'Balance']
        for c, h in enumerate(headers, start=1):
            ws.cell(row=5, column=c, value=h).font = Font(bold=True)

        row_num = 6
        total_amount = Decimal('0.00')
        total_paid = Decimal('0.00')
        total_balance = Decimal('0.00')

        for inv in invoices.order_by('-issue_date'):
            ws.cell(row=row_num, column=1, value=inv.invoice_number)
            ws.cell(row=row_num, column=2, value=inv.issue_date.strftime('%Y-%m-%d') if inv.issue_date else '')
            ws.cell(row=row_num, column=3, value=getattr(inv.student, 'full_name', ''))
            ws.cell(row=row_num, column=4, value=getattr(inv.student, 'admission_number', ''))
            ws.cell(row=row_num, column=5, value=getattr(inv.student, 'current_class', ''))
            c6 = ws.cell(row=row_num, column=6, value=float(inv.total_amount or 0))
            format_money_cell(c6)
            c7 = ws.cell(row=row_num, column=7, value=float(inv.amount_paid or 0))
            format_money_cell(c7)
            c8 = ws.cell(row=row_num, column=8, value=float(inv.balance or 0))
            format_money_cell(c8)
            total_amount += Decimal(inv.total_amount or 0)
            total_paid += Decimal(inv.amount_paid or 0)
            total_balance += Decimal(inv.balance or 0)
            row_num += 1

        # totals
        ws.cell(row=row_num, column=1, value='Totals').font = Font(bold=True)
        c6 = ws.cell(row=row_num, column=6, value=float(total_amount))
        format_money_cell(c6)
        c7 = ws.cell(row=row_num, column=7, value=float(total_paid))
        format_money_cell(c7)
        c8 = ws.cell(row=row_num, column=8, value=float(total_balance))
        format_money_cell(c8)

        for col in range(1, len(headers) + 1):
            ws.column_dimensions[get_column_letter(col)].width = 18

        bytes_data = workbook_to_bytes(wb)
        filename = f"invoices-{datetime.now().strftime('%Y%m%d-%H%M')}.xlsx"
        return xlsx_response(bytes_data, filename)


class InvoiceReportPDFView(LoginRequiredMixin, View):
    def get(self, request):
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        academic_year = request.GET.get('academic_year')
        term = request.GET.get('term')
        student_class = request.GET.get('student_class')

        invoices = Invoice.objects.select_related('student', 'term__academic_year').all()
        if academic_year:
            invoices = invoices.filter(term__academic_year__pk=academic_year)
        if term:
            invoices = invoices.filter(term__term=term)
        if start_date:
            invoices = invoices.filter(issue_date__gte=start_date)
        if end_date:
            invoices = invoices.filter(issue_date__lte=end_date)
        if student_class:
            invoices = invoices.filter(student__current_class=student_class)

        rows = []
        totals = {'total_amount': Decimal('0.00'), 'total_paid': Decimal('0.00'), 'total_balance': Decimal('0.00')}
        for inv in invoices.order_by('-issue_date'):
            rows.append({
                'invoice_number': inv.invoice_number,
                'issue_date': inv.issue_date,
                'student': getattr(inv.student, 'full_name', ''),
                'admission': getattr(inv.student, 'admission_number', ''),
                'student_class': getattr(inv.student, 'current_class', ''),
                'total_amount': inv.total_amount or Decimal('0.00'),
                'amount_paid': inv.amount_paid or Decimal('0.00'),
                'balance': inv.balance or Decimal('0.00'),
            })
            totals['total_amount'] += Decimal(inv.total_amount or 0)
            totals['total_paid'] += Decimal(inv.amount_paid or 0)
            totals['total_balance'] += Decimal(inv.balance or 0)

        context = {
            'rows': rows,
            'totals': totals,
            'SCHOOL_NAME': getattr(settings, 'SCHOOL_NAME', ''),
            'SCHOOL_LOGO_URL': getattr(settings, 'SCHOOL_LOGO_URL', ''),
            'SCHOOL_ADDRESS': getattr(settings, 'SCHOOL_ADDRESS', ''),
            'SCHOOL_CONTACT': getattr(settings, 'SCHOOL_CONTACT', ''),
            'generated_by': request.user.get_full_name(),
            'generated_on': datetime.now(),
        }

        html_string = render_to_string('reports/pdf/invoice_report_pdf.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri('/'))
        pdf_bytes = html.write_pdf()
        filename = f"invoices-{datetime.now().strftime('%Y%m%d-%H%M')}.pdf"
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response


# ---------- Fees Collection Exports ----------
class FeesCollectionExcelView(LoginRequiredMixin, View):
    """
    Exports Payments / Collections to Excel.
    Filters: start_date, end_date, academic_year, term, student_class
    """
    def get(self, request):
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        academic_year = request.GET.get('academic_year')
        term = request.GET.get('term')
        student_class = request.GET.get('student_class')

        payments = Payment.objects.select_related('invoice__student', 'invoice').all()
        if start_date:
            payments = payments.filter(payment_date__gte=start_date)
        if end_date:
            payments = payments.filter(payment_date__lte=end_date)
        if academic_year:
            payments = payments.filter(invoice__term__academic_year__pk=academic_year)
        if term:
            payments = payments.filter(invoice__term__term=term)
        if student_class:
            payments = payments.filter(invoice__student__current_class=student_class)

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Collections"

        add_common_header(ws, "Fees Collection Report")
        headers = ['Payment Date', 'Invoice #', 'Student', 'Admission #', 'Class', 'Amount', 'Method', 'Reference']
        for c, h in enumerate(headers, start=1):
            ws.cell(row=5, column=c, value=h).font = Font(bold=True)

        row_num = 6
        total_amount = Decimal('0.00')
        for p in payments.order_by('-payment_date'):
            ws.cell(row=row_num, column=1, value=p.payment_date.strftime('%Y-%m-%d') if p.payment_date else '')
            ws.cell(row=row_num, column=2, value=getattr(p.invoice, 'invoice_number', ''))
            ws.cell(row=row_num, column=3, value=getattr(p.invoice.student, 'full_name', ''))
            ws.cell(row=row_num, column=4, value=getattr(p.invoice.student, 'admission_number', ''))
            ws.cell(row=row_num, column=5, value=getattr(p.invoice.student, 'current_class', ''))
            c6 = ws.cell(row=row_num, column=6, value=float(p.amount or 0))
            format_money_cell(c6)
            ws.cell(row=row_num, column=7, value=getattr(p, 'method', ''))
            ws.cell(row=row_num, column=8, value=getattr(p, 'reference', ''))
            total_amount += Decimal(p.amount or 0)
            row_num += 1

        ws.cell(row=row_num, column=1, value='Totals').font = Font(bold=True)
        c6 = ws.cell(row=row_num, column=6, value=float(total_amount))
        format_money_cell(c6)

        for col in range(1, len(headers) + 1):
            ws.column_dimensions[get_column_letter(col)].width = 18

        bytes_data = workbook_to_bytes(wb)
        filename = f"fees-collections-{datetime.now().strftime('%Y%m%d-%H%M')}.xlsx"
        return xlsx_response(bytes_data, filename)


class FeesCollectionPDFView(LoginRequiredMixin, View):
    def get(self, request):
        start_date = request.GET.get('start_date')
        end_date = request.GET.get('end_date')
        academic_year = request.GET.get('academic_year')
        term = request.GET.get('term')
        student_class = request.GET.get('student_class')

        payments = Payment.objects.select_related('invoice__student', 'invoice').all()
        if start_date:
            payments = payments.filter(payment_date__gte=start_date)
        if end_date:
            payments = payments.filter(payment_date__lte=end_date)
        if academic_year:
            payments = payments.filter(invoice__term__academic_year__pk=academic_year)
        if term:
            payments = payments.filter(invoice__term__term=term)
        if student_class:
            payments = payments.filter(invoice__student__current_class=student_class)

        rows = []
        total_amount = Decimal('0.00')
        for p in payments.order_by('-payment_date'):
            rows.append({
                'payment_date': p.payment_date,
                'invoice_number': getattr(p.invoice, 'invoice_number', ''),
                'student': getattr(p.invoice.student, 'full_name', ''),
                'admission': getattr(p.invoice.student, 'admission_number', ''),
                'student_class': getattr(p.invoice.student, 'current_class', ''),
                'amount': p.amount or Decimal('0.00'),
                'method': getattr(p, 'method', ''),
                'reference': getattr(p, 'reference', ''),
            })
            total_amount += Decimal(p.amount or 0)

        context = {
            'rows': rows,
            'totals': {'amount': total_amount},
            'SCHOOL_NAME': getattr(settings, 'SCHOOL_NAME', ''),
            'SCHOOL_LOGO_URL': getattr(settings, 'SCHOOL_LOGO_URL', ''),
            'SCHOOL_ADDRESS': getattr(settings, 'SCHOOL_ADDRESS', ''),
            'SCHOOL_CONTACT': getattr(settings, 'SCHOOL_CONTACT', ''),
            'generated_by': request.user.get_full_name(),
            'generated_on': datetime.now(),
        }

        html_string = render_to_string('reports/pdf/fees_collection_report_pdf.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri('/'))
        pdf_bytes = html.write_pdf()
        filename = f"fees-collections-{datetime.now().strftime('%Y%m%d-%H%M')}.pdf"
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response