# Generated by Django 4.2.13 on 2025-12-21 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "academics",
            "0008_transportfee_half_amount_alter_transportfee_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("invoice_summary", "Invoice Summary"),
                            ("collection_analysis", "Fees Collection Analysis"),
                            ("outstanding", "Outstanding Balances"),
                            ("transport", "Transport Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("term", models.CharField(blank=True, max_length=20, null=True)),
                ("params", models.JSONField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
