# Generated by Django 4.2.13 on 2026-01-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_reportrequest_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportrequest",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("invoice_summary", "Invoice Summary"),
                    ("collection_analysis", "Fees Collection Analysis"),
                    ("outstanding", "Outstanding Balances"),
                    ("transport", "Transport Report"),
                    ("transferred_students", "Transferred Students Report"),
                    ("admitted_students", "Admitted Students Report"),
                ],
                max_length=50,
            ),
        ),
    ]
