# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("reports", "0003_alter_reportrequest_report_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this report request belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_requests",
                to="core.organization",
            ),
        ),
    ]
