# Generated by Django 4.2.13 on 2026-03-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportrequest_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='report_type',
            field=models.CharField(choices=[('invoice_summary', 'Invoice Summary'), ('collection_analysis', 'Fees Collection Analysis'), ('outstanding', 'Outstanding Balances'), ('transport', 'Transport Report'), ('transferred_students', 'Transferred Students Report'), ('graduated_students', 'Graduated Students Report'), ('admitted_students', 'Admitted Students Report'), ('other_items', 'Other Items Invoice Report')], max_length=50),
        ),
    ]
