# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportrequest_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='report_type',
            field=models.CharField(
                choices=[
                    ('invoice_summary', 'Invoice Summary'),
                    ('collection_analysis', 'Fees Collection Analysis'),
                    ('outstanding', 'Outstanding Balances'),
                    ('overpayments', 'Overpayments Report'),
                    ('transport', 'Transport Report'),
                    ('transferred_students', 'Transferred Students Report'),
                    ('graduated_students', 'Graduated Students Report'),
                    ('admitted_students', 'Admitted Students Report'),
                    ('other_items', 'Other Items Invoice Report'),
                ],
                max_length=50,
            ),
        ),
    ]
