# Generated by Django 4.2.13 on 2026-02-01 15:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        (
            "academics",
            "0012_academicyear_organization_attendance_organization_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allowance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "allowance_type",
                    models.CharField(
                        choices=[
                            ("housing", "Housing Allowance"),
                            ("transport", "Transport Allowance"),
                            ("medical", "Medical Allowance"),
                            ("lunch", "Lunch Allowance"),
                            ("overtime", "Overtime"),
                            ("bonus", "Bonus"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed amount (0 if percentage-based)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_percentage",
                    models.BooleanField(
                        default=False,
                        help_text="If True, amount is percentage of basic salary",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of basic salary (if is_percentage=True)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True, help_text="Whether allowance is subject to tax"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this allowance belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allowances",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "allowances",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Deduction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("nhif", "NHIF"),
                            ("nssf", "NSSF"),
                            ("paye", "PAYE"),
                            ("loan", "Loan"),
                            ("advance", "Salary Advance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed amount (0 if percentage-based or calculated)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_percentage",
                    models.BooleanField(
                        default=False,
                        help_text="If True, amount is percentage of gross salary",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of gross salary (if is_percentage=True)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_calculated",
                    models.BooleanField(
                        default=False,
                        help_text="If True, deduction is calculated based on brackets (e.g., NHIF, PAYE)",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this deduction belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deductions",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "deductions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_allowances",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "nhif",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "nssf_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "nssf_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "paye",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this payroll entry belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_entries",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_entries",
                "ordering": ["staff__staff_number"],
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Grade name, e.g., 'T-Scale 1', 'Administrative Grade 1'",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this grade",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Basic monthly salary",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this salary structure belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salary_structures",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "salary_structures",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffSalary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this salary becomes effective"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this salary ends (if applicable)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "allowances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff_salaries",
                        to="payroll.allowance",
                    ),
                ),
                (
                    "deductions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="staff_salaries",
                        to="payroll.deduction",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this staff salary belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_salaries",
                        to="core.organization",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        help_text="Salary structure/grade",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_salaries",
                        to="payroll.salarystructure",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        help_text="Staff member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary",
                        to="academics.staff",
                    ),
                ),
            ],
            options={
                "db_table": "staff_salaries",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="payslips/"),
                ),
                ("is_downloaded", models.BooleanField(default=False)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payslips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this payslip belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="core.organization",
                    ),
                ),
                (
                    "payroll_entry",
                    models.OneToOneField(
                        help_text="Payroll entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip",
                        to="payroll.payrollentry",
                    ),
                ),
            ],
            options={
                "db_table": "payslips",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("period_month", models.PositiveIntegerField(help_text="Month (1-12)")),
                (
                    "period_year",
                    models.PositiveIntegerField(help_text="Year (e.g., 2025)"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Whether payroll is finalized"
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this payroll period belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_periods",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_periods",
                "ordering": ["-period_year", "-period_month"],
                "unique_together": {("organization", "period_month", "period_year")},
            },
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="payroll_period",
            field=models.ForeignKey(
                help_text="Payroll period",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="payroll.payrollperiod",
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="staff",
            field=models.ForeignKey(
                help_text="Staff member",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_entries",
                to="academics.staff",
            ),
        ),
        migrations.AddField(
            model_name="payrollentry",
            name="staff_salary",
            field=models.ForeignKey(
                help_text="Staff salary configuration",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_entries",
                to="payroll.staffsalary",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollentry",
            unique_together={("payroll_period", "staff")},
        ),
        migrations.CreateModel(
            name="PayrollDeduction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated deduction amount for this period",
                        max_digits=10,
                    ),
                ),
                (
                    "deduction",
                    models.ForeignKey(
                        help_text="Deduction type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_deductions",
                        to="payroll.deduction",
                    ),
                ),
                (
                    "payroll_entry",
                    models.ForeignKey(
                        help_text="Payroll entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deduction_items",
                        to="payroll.payrollentry",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_deductions",
                "unique_together": {("payroll_entry", "deduction")},
            },
        ),
        migrations.CreateModel(
            name="PayrollAllowance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated allowance amount for this period",
                        max_digits=10,
                    ),
                ),
                (
                    "allowance",
                    models.ForeignKey(
                        help_text="Allowance type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_allowances",
                        to="payroll.allowance",
                    ),
                ),
                (
                    "payroll_entry",
                    models.ForeignKey(
                        help_text="Payroll entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_items",
                        to="payroll.payrollentry",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_allowances",
                "unique_together": {("payroll_entry", "allowance")},
            },
        ),
    ]
