# Generated by Django 4.2.13 on 2026-03-22 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('sms_account_number', models.CharField(help_text="Unique account number for SMS purchases (e.g., 'SMS001')", max_length=50, unique=True)),
                ('sms_balance', models.IntegerField(default=0, help_text='SMS credits available')),
                ('sms_price_per_unit', models.DecimalField(decimal_places=2, default=1.0, help_text='Price per SMS credit in KSH', max_digits=10)),
                ('imarabiz_shortcode', models.CharField(blank=True, default='SWIFT_RE_TECH', help_text="ImaraBiz shortcode for this organization (e.g., 'KALIMONI_FP'). Leave empty to use company default.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sms_count', models.IntegerField(default=1, help_text='Number of SMS sent')),
                ('purpose', models.CharField(blank=True, help_text="Purpose (e.g., 'low_balance_alert', 'payment_confirmation', 'manual')", max_length=100)),
                ('balance_before', models.IntegerField(help_text='SMS balance before this usage')),
                ('balance_after', models.IntegerField(help_text='SMS balance after this usage')),
                ('notification_ids', models.JSONField(blank=True, help_text='List of SMSNotification IDs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_usage_logs', to='core.organization')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_sms_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Usage Log',
                'verbose_name_plural': 'SMS Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='swift_sms_c_organiz_acacc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSPurchaseTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in KSH', max_digits=10)),
                ('sms_credits', models.IntegerField(help_text='Number of SMS credits purchased')),
                ('price_per_sms', models.DecimalField(decimal_places=2, help_text='Price per SMS at time of purchase', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('bank_reference', models.CharField(db_index=True, help_text='Bank transaction reference', max_length=100, unique=True)),
                ('kcb_channel_code', models.CharField(blank=True, max_length=20)),
                ('kcb_timestamp', models.CharField(blank=True, max_length=50)),
                ('kcb_till_number', models.CharField(blank=True, max_length=50)),
                ('kcb_customer_mobile', models.CharField(blank=True, max_length=20)),
                ('kcb_customer_name', models.CharField(blank=True, max_length=255)),
                ('kcb_narration', models.TextField(blank=True)),
                ('kcb_balance', models.CharField(blank=True, help_text='Account balance after transaction from KCB', max_length=50)),
                ('raw_request_data', models.JSONField(blank=True, help_text='Raw KCB notification data', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='Organization that purchased SMS credits', on_delete=django.db.models.deletion.PROTECT, related_name='sms_purchases', to='core.organization')),
            ],
            options={
                'verbose_name': 'SMS Purchase Transaction',
                'verbose_name_plural': 'SMS Purchase Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='swift_sms_c_organiz_a5574c_idx'), models.Index(fields=['status'], name='swift_sms_c_status_27cae9_idx'), models.Index(fields=['bank_reference'], name='swift_sms_c_bank_re_9f65d8_idx')],
            },
        ),
    ]
