# Generated by Django 4.2.13 on 2025-12-02 07:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("year", models.PositiveIntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "academic_years",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=10,
                    ),
                ),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
            ],
            options={
                "db_table": "attendance",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("pp1", "PP1"),
                            ("pp2", "PP2"),
                            ("grade_1", "Grade 1"),
                            ("grade_2", "Grade 2"),
                            ("grade_3", "Grade 3"),
                            ("grade_4", "Grade 4"),
                            ("grade_5", "Grade 5"),
                            ("grade_6", "Grade 6"),
                            ("grade_7", "Grade 7"),
                            ("grade_8", "Grade 8"),
                            ("grade_9", "Grade 9"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stream", models.CharField(blank=True, max_length=20)),
                ("capacity", models.PositiveIntegerField(default=40)),
                ("room", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["grade_level", "stream"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("periods_per_week", models.PositiveIntegerField(default=5)),
            ],
            options={
                "db_table": "class_subjects",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("cat", "Continuous Assessment Test"),
                            ("midterm", "Mid-Term Exam"),
                            ("endterm", "End of Term Exam"),
                            ("mock", "Mock Exam"),
                            ("assignment", "Assignment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "exams",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("grade_letter", models.CharField(blank=True, max_length=2)),
                (
                    "points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "grades",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("staff_number", models.CharField(max_length=20, unique=True)),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching Staff"),
                            ("admin", "Administrative Staff"),
                            ("support", "Support Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_number", models.CharField(max_length=20, unique=True)),
                ("tsc_number", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True)),
                ("date_joined", models.DateField()),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("contract", "Contract"),
                            ("parttime", "Part-time"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                ("qualifications", models.TextField(blank=True)),
                ("specialization", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
                "db_table": "staff",
                "ordering": ["staff_number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("grade_levels", models.JSONField(default=list)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("core", "Core Subject"),
                            ("elective", "Elective"),
                            ("activity", "Co-curricular Activity"),
                        ],
                        default="core",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("max_marks", models.PositiveIntegerField(default=100)),
                ("pass_marks", models.PositiveIntegerField(default=40)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("term_1", "Term 1"),
                            ("term_2", "Term 2"),
                            ("term_3", "Term 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("fee_deadline", models.DateField(blank=True, null=True)),
                ("late_fee_start_date", models.DateField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="academics.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "terms",
                "ordering": ["academic_year", "term"],
            },
        ),
        migrations.CreateModel(
            name="TransportRoute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_phone", models.CharField(blank=True, max_length=15)),
                ("vehicle_registration", models.CharField(blank=True, max_length=20)),
                ("pickup_points", models.JSONField(default=list)),
                ("morning_departure", models.TimeField(blank=True, null=True)),
                ("afternoon_departure", models.TimeField(blank=True, null=True)),
                (
                    "term_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "transport_routes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=20)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="academics.staff",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "db_table": "timetables",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
