# Generated by Django 4.2.13 on 2025-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="stream",
            field=models.CharField(
                choices=[("EAST", "East"), ("WEST", "West"), ("SOUTH", "South")],
                default="EAST",
                max_length=10,
            ),
        ),
    ]
