# Generated by Django 4.2.13 on 2025-12-15 07:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_class_stream"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportroute",
            name="term_fee",
        ),
        migrations.AddField(
            model_name="transportroute",
            name="full_trip_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost for a full trip (both ways) for the term.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="transportroute",
            name="half_trip_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cost for a half trip (one way) for the term.",
                max_digits=10,
            ),
        ),
    ]
