# Generated by Django 4.2.13 on 2025-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_remove_transportroute_term_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("pp1", "PP1"),
                    ("pp2", "PP2"),
                    ("play_group", "Play Group"),
                    ("grade_1", "Grade 1"),
                    ("grade_2", "Grade 2"),
                    ("grade_3", "Grade 3"),
                    ("grade_4", "Grade 4"),
                    ("grade_5", "Grade 5"),
                    ("grade_6", "Grade 6"),
                    ("grade_7", "Grade 7"),
                    ("grade_8", "Grade 8"),
                    ("grade_9", "Grade 9"),
                ],
                max_length=20,
            ),
        ),
    ]
