# Generated by Django 4.2.13 on 2025-12-19 10:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_alter_class_grade_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportroute",
            name="afternoon_departure",
        ),
        migrations.RemoveField(
            model_name="transportroute",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="transportroute",
            name="driver_phone",
        ),
        migrations.RemoveField(
            model_name="transportroute",
            name="full_trip_amount",
        ),
        migrations.RemoveField(
            model_name="transportroute",
            name="half_trip_amount",
        ),
        migrations.RemoveField(
            model_name="transportroute",
            name="morning_departure",
        ),
        migrations.RemoveField(
            model_name="transportroute",
            name="vehicle_registration",
        ),
        migrations.AddField(
            model_name="transportroute",
            name="code",
            field=models.CharField(default="N/A", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportroute",
            name="dropoff_points",
            field=models.TextField(
                blank=True, help_text="List of drop-off points, one per line"
            ),
        ),
        migrations.AlterField(
            model_name="transportroute",
            name="pickup_points",
            field=models.TextField(
                blank=True, help_text="List of pickup points, one per line"
            ),
        ),
        migrations.CreateModel(
            name="TransportFee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("term_1", "Term 1"),
                            ("term_2", "Term 2"),
                            ("term_3", "Term 3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transport fee amount for this route, term, and academic year",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_fees",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="academics.transportroute",
                    ),
                ),
            ],
            options={
                "db_table": "transport_fees",
                "ordering": ["route__name", "academic_year__year", "term"],
                "unique_together": {("route", "academic_year", "term")},
            },
        ),
    ]
