# Generated by Django 4.2.13 on 2025-12-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_remove_transportroute_afternoon_departure_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transportroute",
            name="code",
        ),
        migrations.AlterField(
            model_name="transportroute",
            name="name",
            field=models.CharField(default="A", max_length=100),
        ),
    ]
