# Generated by Django 4.2.13 on 2025-12-21 10:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_remove_transportroute_code_alter_transportroute_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportfee",
            name="half_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional explicit half-trip fee; if empty half-trip is computed as amount/2",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="transportfee",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Full-trip transport fee for this route, term, and academic year",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="transportroute",
            name="name",
            field=models.CharField(default="Route", max_length=100),
        ),
    ]
