# Generated by Django 4.2.13 on 2025-12-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0008_transportfee_half_amount_alter_transportfee_amount_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransportFee",
        ),
    ]
