# Generated by Django 4.2.13 on 2025-12-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_delete_transportfee"),
        ("students", "0009_alter_student_transport_route"),
        ("finance", "0007_alter_invoiceitem_transport_route"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransportRoute",
        ),
    ]
