# Generated by Django 4.2.13 on 2025-12-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_delete_transportroute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="capacity",
        ),
    ]
