# Generated by Django 4.2.13 on 2026-02-01 11:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("students", "0014_parent_organization_student_organization"),
        ("academics", "0011_remove_capacity_from_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this academic year belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_years",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this attendance record belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this class belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this department belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this exam belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this grade belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grades",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this staff member belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this subject belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this term belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terms",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this timetable entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timetable_entries",
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "overall_grade",
                    models.CharField(
                        blank=True,
                        help_text="Overall grade (e.g., A, B+, B)",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, help_text="Class position", null=True
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "average_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("teacher_comments", models.TextField(blank=True)),
                ("principal_comments", models.TextField(blank=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Published report cards are visible to parents",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_cards",
                        to="academics.class",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_cards_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this report card belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="core.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "db_table": "report_cards",
                "ordering": ["-academic_year__year", "-term", "student__last_name"],
                "unique_together": {("student", "term")},
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("casual", "Casual Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_applications_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this leave application belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_applications",
                        to="core.organization",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="academics.staff",
                    ),
                ),
            ],
            options={
                "db_table": "leave_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportCardItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Grade letter (e.g., A, B+, B)",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="academics.reportcard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_card_items",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "report_card_items",
                "ordering": ["subject__name"],
                "unique_together": {("report_card", "subject")},
            },
        ),
    ]
