# Generated by Django 4.2.13 on 2026-05-01 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('academics', '0013_repair_current_term_and_year_per_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermTransitionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'term_transition_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='unique_academic_year_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('organization', 'academic_year', 'term'), name='unique_term_per_organization_year'),
        ),
        migrations.AddField(
            model_name='termtransitionlog',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_transitions_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termtransitionlog',
            name='new_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transition_logs', to='academics.term'),
        ),
        migrations.AddField(
            model_name='termtransitionlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='term_transition_logs', to='core.organization'),
        ),
        migrations.AddField(
            model_name='termtransitionlog',
            name='previous_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transition_logs', to='academics.term'),
        ),
        migrations.AddConstraint(
            model_name='termtransitionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('dry_run', False)), fields=('organization', 'previous_term', 'new_term'), name='unique_executed_term_transition_per_org'),
        ),
    ]
