# Generated by Django 4.2.13 on 2025-12-30 05:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_tables_if_not_exist(apps, schema_editor):
    """Create tables only if they don't exist (migrating from academics app)"""
    existing_tables = set(schema_editor.connection.introspection.table_names())

    with schema_editor.connection.cursor() as cursor:
        routes_exists = "transport_routes" in existing_tables
        fees_exists = "transport_fees" in existing_tables

        # If tables don't exist, create them
        if not routes_exists:
            cursor.execute("""
                CREATE TABLE transport_routes (
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    id UUID NOT NULL PRIMARY KEY,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    name VARCHAR(100) NOT NULL DEFAULT 'Route',
                    description TEXT NOT NULL,
                    pickup_points TEXT NOT NULL,
                    dropoff_points TEXT NOT NULL
                );
            """)
        
        if not fees_exists:
            cursor.execute("""
                CREATE TABLE transport_fees (
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL,
                    id UUID NOT NULL PRIMARY KEY,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    term VARCHAR(10) NOT NULL,
                    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
                    half_amount NUMERIC(10, 2),
                    academic_year_id UUID NOT NULL,
                    route_id UUID NOT NULL,
                    CONSTRAINT transport_fees_academic_year_id_fkey 
                        FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE CASCADE,
                    CONSTRAINT transport_fees_route_id_fkey 
                        FOREIGN KEY (route_id) REFERENCES transport_routes(id) ON DELETE CASCADE,
                    CONSTRAINT transport_fees_route_id_academic_year_id_term_key 
                        UNIQUE (route_id, academic_year_id, term)
                );
            """)


def reverse_func(apps, schema_editor):
    """Reverse migration - don't drop tables as they may be in use"""
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0009_delete_transportfee"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_tables_if_not_exist, reverse_func),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="TransportRoute",
                    fields=[
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("is_active", models.BooleanField(default=True)),
                        ("name", models.CharField(default="Route", max_length=100)),
                        ("description", models.TextField(blank=True)),
                        (
                            "pickup_points",
                            models.TextField(
                                blank=True, help_text="List of pickup points, one per line"
                            ),
                        ),
                        (
                            "dropoff_points",
                            models.TextField(
                                blank=True, help_text="List of drop-off points, one per line"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "transport_routes",
                        "ordering": ["name"],
                    },
                ),
                migrations.CreateModel(
                    name="TransportFee",
                    fields=[
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("is_active", models.BooleanField(default=True)),
                        (
                            "term",
                            models.CharField(
                                choices=[
                                    ("term_1", "Term 1"),
                                    ("term_2", "Term 2"),
                                    ("term_3", "Term 3"),
                                ],
                                max_length=10,
                            ),
                        ),
                        (
                            "amount",
                            models.DecimalField(
                                decimal_places=2,
                                default=Decimal("0.00"),
                                help_text="Full-trip transport fee for this route, term, and academic year",
                                max_digits=10,
                                validators=[
                                    django.core.validators.MinValueValidator(Decimal("0.00"))
                                ],
                            ),
                        ),
                        (
                            "half_amount",
                            models.DecimalField(
                                blank=True,
                                decimal_places=2,
                                help_text="Optional explicit half-trip fee; if empty half-trip is computed as amount/2",
                                max_digits=10,
                                null=True,
                                validators=[
                                    django.core.validators.MinValueValidator(Decimal("0.00"))
                                ],
                            ),
                        ),
                        (
                            "academic_year",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="transport_fees",
                                to="academics.academicyear",
                            ),
                        ),
                        (
                            "route",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="fees",
                                to="transport.transportroute",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "transport_fees",
                        "ordering": ["route__name", "academic_year__year", "term"],
                        "unique_together": {("route", "academic_year", "term")},
                    },
                ),
            ],
        ),
    ]
