# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("transport", "0002_create_transport_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="transportfee",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this transport fee belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_fees",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="transportroute",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this transport route belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_routes",
                to="core.organization",
            ),
        ),
    ]
