# Generated by Django 4.2.13 on 2025-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other_income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherincomeinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
