# Generated by Django 4.2.13 on 2026-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("other_income", "0002_alter_otherincomeinvoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="otherincomeinvoice",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this other income invoice belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="other_income_invoices",
                to="core.organization",
            ),
        ),
    ]
