# Generated by Django 4.2.13 on 2026-03-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("other_income", "0003_otherincomeinvoice_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="otherincomeinvoice",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otherincomeinvoice",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="other_income_invoices_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
